name: e_commerce_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

  #---------PACKAGES---------#

dependencies:
  flutter:
    sdk: flutter

  #UTILITY PACKAGES

  http: ^1.1.0

  intl: ^0.19.0

  logger: ^2.0.1

  url_launcher: ^6.1.12

  flutter_native_splash: ^2.3.13

  smooth_page_indicator: ^1.1.0

  #icons

  iconsax: ^0.0.8

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  get_storage: ^2.1.1

  #state management

get: ^4.6.5

# product specific

assets:
  - assets/icons/logo-black.png
  - assets/images/OnBoardingImage.gif

#---------./ PACKAGES END---------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  #---------LOCAL ASSETS---------#

  assets:
    - assets/icons/brands/
    - assets/images/
    # - assets/icons/brands
    # - assets/images

  #---------LOCAL fonts---------#
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Light.ttf
  #         weight: 300
